### PR TITLE
Batch Pipeline Fix & Socket Reconnection Fix

### PR DESCRIPTION
**Pull request by kevinstyp**

### CODE REVIEW

**Comment by kevinstyp** [comment]
The former fix in commit 1f490b81f5dc83b69170ba90203d133cf90186b0 called the reconnection method indefinetely often after a timeout which could eventually / potentially lead to a out of memory bug (see also line 115).
The currently implemented approach does drop the sample and closes the connection completely, which did not happen properly as the super-class kept its outputstream somehow. For the next sample the writeSample() method notices the missing socket and opens a new connection then.
With the current solution the connection will be established again, although the sample will be dropped, which could be optimized in the future.

**Comment by alek-thunder** [comment]
Ok, I get the idea. But still, the reconnection will be tried once when a sample arrives. When line 67 times out, a respective SocketTimeoutException will be thrown. You will end up in line 72 which returns null. This lets the super class just return without doing anything. Therefore, every TCP_CONNECT_TIMEOUT_MILLIS you will lose a sample. I am still not sure whether this is the intended behavior.

**Comment by kevinstyp** [comment]
This is "intended behaviour". As long as the socket still cannot connect (which is the case when the set timeout runs out), we will continue to drop the incoming samples until the connection of the socket could be established again.

**Comment by alek-thunder** [comment]
I would argue that it is better to keep the sample on hold until the connection is established again in order to not loose data.
@antongulenko , @flohannes , @mwallschlaeger , @srnbckr whats your opinion on this?

**Comment by antongulenko** [comment]
Line 78 of TcpSink is the main change in this PR, which is a valid Bugfix for the intended behavior. Currently, a failed connection leads to dropped samples, there is no buffering of pending samples (in no implementation of Bitflow). This would be indeed a good addition, but the bugfix in this PR is still valid (before the fix, a lost connection would not be recovered at all).

**Comment by antongulenko** [comment]
Merging

**Pull request merged**
